version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    network_mode: host

  api-service:
    image: 709256896859.dkr.ecr.us-east-2.amazonaws.com/verzel_backend:latest
    container_name: api-service
    restart: unless-stopped
    env_file:
      - env/env.txt
    ports:
      - "5000:5000"
    command: python app.py
    network_mode: host
    depends_on:
      - db


volumes:
  my-db:
